### ISSUE TITLE
Validate cache fails on first run

### ISSUE THREAD

**Issue by rafis** [zero88/gh-registry#2]
On the first run the cache is empty and "Validate cache" step fails:
```
      - name: Validate cache
        run: |
          docker buildx imagetools inspect localhost:5000/test:buildcache
```

> Run docker buildx imagetools inspect localhost:5000/test:buildcache
> error: localhost:5000/test:buildcache: not found
> Error: Process completed with exit code 1.

**Comment by zero88** [comment]
@rafis you can use

```yaml
- name: Validate cache
  run: |
    docker buildx imagetools inspect localhost:5000/${{ env.APP_IMAGE }}:buildcache || echo "Not Found"
```
